export const ADD_NOTE='ADD_NOTE'
export const ACCESS_ALL='ACCESS_ALL'
export const DELETE_NOTE="DELETE_NOTE"
export const ADD_TO_FAVORITE ='ADD_TO_FAVORITE'
export const ACCESS_FAVORITE="ACCESS_FAVORITE"
export const REMOVE_FROM_FAVORITE="REMOVE_FROM_FAVORITE"